import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "@supabase/supabase-js";
import { Image } from "https://deno.land/x/imagescript@1.3.0/mod.ts";

const WORLD_IMAGERY_TILE_BASE="https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile";
const WORLD_STREET_TILE_BASE="https://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile";
const WORLD_LABELS_TILE_BASE="https://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile";
const W=512,CTX_H=256,PLUME_H=320,TILE=256,SPANS=[300,500,1000,2000],CTX_SPAN=5000,PLUME_SPAN=220000;
function json(x:unknown,s=200){return new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json"}})}
function zoomForSpan(lat:number,spanM:number,pixels:number){const mpp=Math.max(.4,spanM/pixels);return Math.max(3,Math.min(18,Math.round(Math.log2(156543.03392804097*Math.max(.2,Math.cos(lat*Math.PI/180))/mpp))))}
function worldPixel(lat:number,lon:number,z:number){const scale=TILE*2**z,x=(lon+180)/360*scale,s=Math.sin(lat*Math.PI/180),y=(.5-Math.log((1+s)/(1-s))/(4*Math.PI))*scale;return{x,y}}
async function tile(base:string,z:number,x:number,y:number,required=true){const r=await fetch(`${base}/${z}/${y}/${x}`,{signal:AbortSignal.timeout(12000),headers:{"user-agent":"firewatch-media/1.0"}});if(!r.ok){if(required)throw new Error("tile "+r.status);return null}return Image.decode(new Uint8Array(await r.arrayBuffer()))}
async function crop(base:string,lat:number,lon:number,span:number,w:number,h:number){const z=zoomForSpan(lat,span,w),c=worldPixel(lat,lon,z),mpp=156543.03392804097*Math.cos(lat*Math.PI/180)/2**z,cw=Math.max(256,Math.round(span/mpp)),ch=Math.max(192,Math.round(cw*h/w)),sx=c.x-cw/2,sy=c.y-ch/2,ex=sx+cw,ey=sy+ch,minX=Math.floor(sx/TILE),maxX=Math.floor((ex-1)/TILE),minY=Math.floor(sy/TILE),maxY=Math.floor((ey-1)/TILE),m=new Image((maxX-minX+1)*TILE,(maxY-minY+1)*TILE);for(let ty=minY;ty<=maxY;ty++)for(let tx=minX;tx<=maxX;tx++){const t=await tile(base,z,tx,ty);if(t)m.composite(t,(tx-minX)*TILE,(ty-minY)*TILE)}m.crop(Math.round(sx-minX*TILE),Math.round(sy-minY*TILE),cw,ch).resize(w,h);return m}
function score(img:any){const b=img.bitmap as Uint8ClampedArray,w=img.width,h=img.height,step=Math.max(8,Math.round(Math.min(w,h)/48));let n=0,sum=0,sum2=0,g=0,gn=0;for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step){const i=(y*w+x)*4,l=.2126*b[i]+.7152*b[i+1]+.0722*b[i+2];sum+=l;sum2+=l*l;n++;if(x+step<w){const j=(y*w+x+step)*4,l2=.2126*b[j]+.7152*b[j+1]+.0722*b[j+2];g+=Math.abs(l2-l);gn++}}const v=n?Math.max(0,sum2/n-(sum/n)**2):0;return Math.sqrt(v)+(gn?g/gn:0)*1.8}
const PIN=`<svg xmlns="http://www.w3.org/2000/svg" width="46" height="60"><path d="M23 2C11 2 2 11 2 23c0 15 21 35 21 35s21-20 21-35C44 11 35 2 23 2z" fill="#f44336" stroke="#b71c1c" stroke-width="2"/><circle cx="23" cy="23" r="8" fill="#b71c1c"/></svg>`;
async function pin(img:any){const p=await Image.renderSVG(PIN);img.composite(p,Math.round(img.width/2-p.width/2),Math.round(img.height/2-p.height+2))}
async function banner(text:string,width:number){const s=text.replace(/&/g,"&amp;").replace(/</g,"&lt;");return Image.renderSVG(`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="34"><rect width="100%" height="100%" fill="rgba(0,0,0,.64)"/><text x="10" y="23" font-family="Arial" font-size="15" fill="white">${s}</text></svg>`)}
async function plumeOverlay(dir:number){const cx=W/2,cy=PLUME_H/2+8,r=132,to=(d:number,rr:number)=>{const a=(d-90)*Math.PI/180;return[cx+Math.cos(a)*rr,cy+Math.sin(a)*rr]};const p1=to(dir-22.5,r),p2=to(dir+22.5,r),tip=to(dir,r);const rings=[10,25,50,100].map(k=>`<circle cx="${cx}" cy="${cy}" r="${r*k/100}" fill="none" stroke="rgba(255,255,255,.72)" stroke-width="1"/><text x="${cx+r*k/100+3}" y="${cy-3}" fill="white" font-size="11">${k} км</text>`).join("");const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${PLUME_H}"><polygon points="${cx},${cy} ${p1[0]},${p1[1]} ${p2[0]},${p2[1]}" fill="rgba(255,112,67,.22)" stroke="rgba(255,112,67,.95)" stroke-width="2"/>${rings}<line x1="${cx}" y1="${cy}" x2="${tip[0]}" y2="${tip[1]}" stroke="white" stroke-width="3"/><circle cx="${cx}" cy="${cy}" r="6" fill="#f44336"/><text x="12" y="300" fill="white" font-size="14">Расчётный сектор переноса ~${Math.round(dir)}° • не прогноз концентрации дыма</text></svg>`;return Image.renderSVG(svg)}
async function render(lat:number,lon:number,plumeDir?:number|null){let img:any=null,span=SPANS.at(-1)!;for(const s of SPANS){img=await crop(WORLD_IMAGERY_TILE_BASE,lat,lon,s,W,W);span=s;if(score(img)>=22||s===SPANS.at(-1))break}try{const lab=await crop(WORLD_LABELS_TILE_BASE,lat,lon,span,W,W);lab.opacity(.92);img.composite(lab,0,0)}catch{}await pin(img);img.composite(await banner(`Контекст ~${span}×${span} м`,W),0,0);const ctx=await crop(WORLD_STREET_TILE_BASE,lat,lon,CTX_SPAN,W,CTX_H);await pin(ctx);ctx.composite(await banner("Ориентация ~5 км",W),0,0);const hasPlume=Number.isFinite(Number(plumeDir)),totalH=W+CTX_H+(hasPlume?PLUME_H:0),out=new Image(W,totalH);out.composite(img,0,0);out.composite(ctx,0,W);if(hasPlume){const pm=await crop(WORLD_STREET_TILE_BASE,lat,lon,PLUME_SPAN,W,PLUME_H);pm.composite(await plumeOverlay(Number(plumeDir)),0,0);pm.composite(await banner("Прогнозный сектор • обзор ~220 км",W),0,0);out.composite(pm,0,W+CTX_H)}let bytes:Uint8Array,mime="image/png";const enc=(out as any).encodeJPEG;if(typeof enc==="function"){try{bytes=await enc.call(out,82);mime="image/jpeg"}catch{bytes=await out.encode(2)}}else bytes=await out.encode(2);return{blob:new Blob([bytes],{type:mime}),span,bytes:bytes.length}}
async function telegram(token:string,method:string,body:FormData){
  for(let attempt=0;attempt<2;attempt++){
    const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:"POST",body,signal:AbortSignal.timeout(30000)});
    const j=await r.json();
    if(r.ok&&j?.ok)return j.result;
    if(String(j?.description??"").includes("message is not modified"))return {noop:true};
    const retry=Number(j?.parameters?.retry_after??0);
    if((r.status===429||String(j?.description??"").includes("Too Many Requests"))&&retry>0&&retry<=30&&attempt===0){
      await new Promise(res=>setTimeout(res,(retry+1)*1000));
      continue;
    }
    throw new Error("Telegram "+method+": "+(j?.description??r.status));
  }
  throw new Error("Telegram "+method+": retry exhausted");
}
Deno.serve(async(req)=>{
 if(req.method!=="POST")return json({ok:false},405);
 const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),token=Deno.env.get("TELEGRAM_BOT_TOKEN"),chat=Deno.env.get("TELEGRAM_CHAT_ID");
 if(!url||!key||!token||!chat)return json({ok:false,error:"env"},500);
 const sb=createClient(url,key,{auth:{persistSession:false}});const secret=req.headers.get("x-cron-secret")??"";const {data:a}=await sb.rpc("verify_firewatch_cron_secret",{p_secret:secret});if(a!==true)return json({ok:false,error:"unauthorized"},401);
 try{const b=await req.json(),lat=Number(b.lat),lon=Number(b.lon),caption=String(b.caption??""),action=String(b.action??"send"),messageId=Number(b.message_id??0),plumeDir=Number(b.plume_direction_deg);if(!Number.isFinite(lat)||!Number.isFinite(lon)||!caption)return json({ok:false,error:"bad input"},400);if(caption.length>1024)return json({ok:false,error:`caption length ${caption.length} exceeds Telegram media limit 1024`},400);const snap=await render(lat,lon,Number.isFinite(plumeDir)?plumeDir:null),f=new FormData();f.set("chat_id",chat);if(action==="edit"){if(!messageId)return json({ok:false,error:"message_id required"},400);f.set("message_id",String(messageId));f.set("media",JSON.stringify({type:"photo",media:"attach://photo",caption}));f.set("photo",snap.blob,snap.blob.type==="image/jpeg"?"context.jpg":"context.png");await telegram(token,"editMessageMedia",f);return json({ok:true,action:"edit",message_id:messageId,span_m:snap.span,media_bytes:snap.bytes})}f.set("caption",caption);f.set("show_caption_above_media","true");f.set("photo",snap.blob,snap.blob.type==="image/jpeg"?"context.jpg":"context.png");const m=await telegram(token,"sendPhoto",f);return json({ok:true,action:"send",message_id:m.message_id,span_m:snap.span,media_bytes:snap.bytes})}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},502)}
});