-- FIRMSGeoTools Community Edition
-- Clean Core schema v0.1
-- Geography-agnostic: AOI + optional regions.

create extension if not exists postgis with schema extensions;
create extension if not exists pgcrypto with schema extensions;

create table public.project_config (
  id boolean primary key default true check (id),
  project_name text not null default 'FIRMSGeoTools',
  timezone text not null default 'UTC',
  poll_interval_minutes integer not null default 15 check (poll_interval_minutes between 5 and 60),
  event_match_hours integer not null default 24 check (event_match_hours between 1 and 168),
  bootstrap_fresh_hours integer not null default 3 check (bootstrap_fresh_hours between 0 and 24),
  telegram_enabled boolean not null default true,
  dashboard_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.project_config(id) values(true) on conflict do nothing;

create table public.monitoring_areas (
  id bigint generated by default as identity primary key,
  code text unique,
  name text not null,
  geom extensions.geometry(MultiPolygon,4326) not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.regions (
  id bigint generated by default as identity primary key,
  code text unique,
  name text not null,
  source text,
  source_id text,
  geom extensions.geometry(MultiPolygon,4326) not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.fire_events (
  id uuid primary key default gen_random_uuid(),
  region_id bigint references public.regions(id) on delete set null,
  status text not null default 'active' check (status in ('active','inactive','closed')),
  lifecycle_status text not null default 'active' check (lifecycle_status in ('active','closed')),
  first_seen timestamptz not null,
  last_seen timestamptz not null,
  first_latitude double precision not null check(first_latitude between -90 and 90),
  first_longitude double precision not null check(first_longitude between -180 and 180),
  last_latitude double precision not null check(last_latitude between -90 and 90),
  last_longitude double precision not null check(last_longitude between -180 and 180),
  first_location extensions.geography(Point,4326) not null,
  last_location extensions.geography(Point,4326) not null,
  best_latitude double precision,
  best_longitude double precision,
  best_location extensions.geography(Point,4326),
  best_location_resolution_m integer,
  observation_count integer not null default 1 check(observation_count>=1),
  multisource_count integer not null default 1,
  multisource_sources text[] not null default '{}',
  match_radius_m integer not null default 750 check(match_radius_m>0),
  notification_required boolean not null default true,
  telegram_sent boolean not null default false,
  telegram_sent_at timestamptz,
  telegram_message_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check(last_seen>=first_seen)
);

create table public.detections (
  id uuid primary key default gen_random_uuid(),
  detection_hash text not null unique,
  event_id uuid references public.fire_events(id) on delete set null,
  region_id bigint references public.regions(id) on delete set null,
  source text not null,
  satellite text,
  instrument text not null,
  acq_datetime timestamptz not null,
  latitude double precision not null check(latitude between -90 and 90),
  longitude double precision not null check(longitude between -180 and 180),
  location extensions.geography(Point,4326) not null,
  scan double precision,
  track double precision,
  confidence text,
  frp double precision,
  daynight text check(daynight is null or daynight in ('D','N')),
  resolution_m integer,
  raw jsonb,
  received_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table public.system_state (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table public.firms_sources (
  source_id text primary key,
  enabled boolean not null default true,
  resolution_m integer not null,
  match_radius_m integer not null,
  display_name text not null,
  sort_order integer not null default 100
);

insert into public.firms_sources(source_id,resolution_m,match_radius_m,display_name,sort_order) values
('VIIRS_NOAA20_NRT',375,750,'NOAA-20 / VIIRS',10),
('VIIRS_NOAA21_NRT',375,750,'NOAA-21 / VIIRS',20),
('VIIRS_SNPP_NRT',375,750,'Suomi NPP / VIIRS',30),
('MODIS_NRT',1000,1000,'Terra/Aqua / MODIS',40)
on conflict(source_id) do update set
  resolution_m=excluded.resolution_m,
  match_radius_m=excluded.match_radius_m,
  display_name=excluded.display_name,
  sort_order=excluded.sort_order;

create index monitoring_areas_geom_gix on public.monitoring_areas using gist(geom);
create index regions_geom_gix on public.regions using gist(geom);
create index detections_location_gix on public.detections using gist(location);
create index detections_acq_datetime_idx on public.detections(acq_datetime desc);
create index detections_event_id_idx on public.detections(event_id);
create index detections_region_id_idx on public.detections(region_id);
create index fire_events_last_location_gix on public.fire_events using gist(last_location);
create index fire_events_last_seen_idx on public.fire_events(last_seen desc);
create index fire_events_status_last_seen_idx on public.fire_events(status,last_seen desc);
create index fire_events_region_id_idx on public.fire_events(region_id);

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path=public as $$
begin new.updated_at=now(); return new; end $$;

create trigger project_config_set_updated_at before update on public.project_config
for each row execute function public.set_updated_at();
create trigger monitoring_areas_set_updated_at before update on public.monitoring_areas
for each row execute function public.set_updated_at();
create trigger regions_set_updated_at before update on public.regions
for each row execute function public.set_updated_at();
create trigger fire_events_set_updated_at before update on public.fire_events
for each row execute function public.set_updated_at();
create trigger system_state_set_updated_at before update on public.system_state
for each row execute function public.set_updated_at();

create or replace function public.firewatch_runtime_config()
returns jsonb
language sql stable security definer
set search_path=public,extensions,pg_temp
as $$
with a as (
  select extensions.st_extent(geom) box
  from public.monitoring_areas
  where enabled
), c as (
  select * from public.project_config where id=true
)
select jsonb_build_object(
  'project_name',c.project_name,
  'timezone',c.timezone,
  'poll_interval_minutes',c.poll_interval_minutes,
  'event_match_hours',c.event_match_hours,
  'bootstrap_fresh_hours',c.bootstrap_fresh_hours,
  'telegram_enabled',c.telegram_enabled,
  'dashboard_enabled',c.dashboard_enabled,
  'bbox',case when a.box is null then null else jsonb_build_array(
    extensions.st_xmin(a.box),extensions.st_ymin(a.box),
    extensions.st_xmax(a.box),extensions.st_ymax(a.box)
  ) end,
  'sources',coalesce((
    select jsonb_agg(jsonb_build_object(
      'source_id',source_id,'resolution_m',resolution_m,
      'match_radius_m',match_radius_m,'display_name',display_name
    ) order by sort_order)
    from public.firms_sources where enabled
  ),'[]'::jsonb)
)
from a,c;
$$;

create or replace function public.firewatch_point_in_aoi(p_latitude double precision,p_longitude double precision)
returns boolean
language sql stable security definer
set search_path=public,extensions,pg_temp
as $$
select exists(
  select 1 from public.monitoring_areas a
  where a.enabled and extensions.st_covers(
    a.geom,extensions.st_setsrid(extensions.st_makepoint(p_longitude,p_latitude),4326)
  )
);
$$;

create or replace function public.lookup_region_id(p_latitude double precision,p_longitude double precision)
returns bigint
language sql stable security definer
set search_path=public,extensions,pg_temp
as $$
select r.id from public.regions r
where r.enabled and extensions.st_covers(
  r.geom,extensions.st_setsrid(extensions.st_makepoint(p_longitude,p_latitude),4326)
)
order by r.id limit 1;
$$;

create or replace function public.firewatch_set_geography(
  p_aoi jsonb,
  p_regions jsonb default null
)
returns jsonb
language plpgsql security definer
set search_path=public,extensions,pg_temp
as $$
declare
  f jsonb;
  g extensions.geometry;
  n_aoi integer:=0;
  n_regions integer:=0;
begin
  if p_aoi is null or p_aoi->>'type'<>'FeatureCollection' then
    raise exception 'AOI must be a GeoJSON FeatureCollection';
  end if;

  delete from public.monitoring_areas where id is not null;

  for f in select value from jsonb_array_elements(p_aoi->'features') loop
    g:=extensions.st_setsrid(extensions.st_geomfromgeojson((f->'geometry')::text),4326);
    if geometrytype(g)='POLYGON' then g:=extensions.st_multi(g); end if;
    if geometrytype(g)<>'MULTIPOLYGON' then raise exception 'AOI geometry must be Polygon or MultiPolygon'; end if;
    if not extensions.st_isvalid(g) then raise exception 'Invalid AOI geometry'; end if;
    insert into public.monitoring_areas(code,name,geom)
    values(
      nullif(f->'properties'->>'code',''),
      coalesce(nullif(f->'properties'->>'name',''),'Monitoring area'),
      g
    );
    n_aoi:=n_aoi+1;
  end loop;

  delete from public.regions where id is not null;
  if p_regions is not null then
    if p_regions->>'type'<>'FeatureCollection' then
      raise exception 'Regions must be a GeoJSON FeatureCollection';
    end if;
    for f in select value from jsonb_array_elements(p_regions->'features') loop
      g:=extensions.st_setsrid(extensions.st_geomfromgeojson((f->'geometry')::text),4326);
      if geometrytype(g)='POLYGON' then g:=extensions.st_multi(g); end if;
      if geometrytype(g)<>'MULTIPOLYGON' then raise exception 'Region geometry must be Polygon or MultiPolygon'; end if;
      if not extensions.st_isvalid(g) then raise exception 'Invalid region geometry'; end if;
      insert into public.regions(code,name,source,source_id,geom)
      values(
        nullif(coalesce(f->'properties'->>'code',f->'properties'->>'id'),''),
        coalesce(f->'properties'->>'name',f->'properties'->>'NAME_1',f->'properties'->>'shapeName','Region'),
        coalesce(f->'properties'->>'source','user'),
        nullif(f->'properties'->>'source_id',''),
        g
      );
      n_regions:=n_regions+1;
    end loop;
  end if;

  insert into public.system_state(key,value,updated_at)
  values('geography',jsonb_build_object(
    'configured',true,'aoi_features',n_aoi,'region_features',n_regions,'configured_at',now()
  ),now())
  on conflict(key) do update set value=excluded.value,updated_at=excluded.updated_at;

  return jsonb_build_object('ok',true,'aoi_features',n_aoi,'region_features',n_regions,'runtime',public.firewatch_runtime_config());
end;
$$;

create or replace function public.ingest_firms_detection(
  p_source text,p_satellite text,p_instrument text,p_acq_datetime timestamptz,
  p_latitude double precision,p_longitude double precision,
  p_scan double precision default null,p_track double precision default null,
  p_confidence text default null,p_frp double precision default null,
  p_daynight text default null,p_raw jsonb default '{}'::jsonb,
  p_match_radius_m integer default 750,p_match_window_hours integer default 24,
  p_resolution_m integer default null
)
returns jsonb
language plpgsql security definer
set search_path=public,extensions,pg_temp
as $$
declare
  v_point extensions.geography(Point,4326);
  v_region_id bigint;
  v_hash text;
  v_detection_id uuid;
  v_event_id uuid;
  v_existing_event uuid;
  v_new boolean:=false;
begin
  if not public.firewatch_point_in_aoi(p_latitude,p_longitude) then
    return jsonb_build_object('inserted',false,'duplicate',false,'outside_aoi',true,'is_new_event',false,'should_notify',false);
  end if;

  v_point:=extensions.st_setsrid(extensions.st_makepoint(p_longitude,p_latitude),4326)::extensions.geography;
  v_region_id:=public.lookup_region_id(p_latitude,p_longitude);
  v_hash:=encode(extensions.digest(concat_ws('|',
    coalesce(p_source,''),coalesce(p_satellite,''),coalesce(p_instrument,''),
    to_char(p_acq_datetime at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US'),
    to_char(round(p_latitude::numeric,6),'FM999990.000000'),
    to_char(round(p_longitude::numeric,6),'FM999990.000000')
  ),'sha256'),'hex');

  insert into public.detections(
    detection_hash,region_id,source,satellite,instrument,acq_datetime,
    latitude,longitude,location,scan,track,confidence,frp,daynight,resolution_m,raw
  ) values(
    v_hash,v_region_id,p_source,p_satellite,p_instrument,p_acq_datetime,
    p_latitude,p_longitude,v_point,p_scan,p_track,p_confidence,p_frp,p_daynight,p_resolution_m,coalesce(p_raw,'{}'::jsonb)
  )
  on conflict(detection_hash) do nothing returning id into v_detection_id;

  if v_detection_id is null then
    select id,event_id into v_detection_id,v_existing_event from public.detections where detection_hash=v_hash;
    return jsonb_build_object('inserted',false,'duplicate',true,'outside_aoi',false,'detection_id',v_detection_id,'event_id',v_existing_event,'is_new_event',false,'should_notify',false);
  end if;

  select e.id into v_event_id
  from public.fire_events e
  where e.status in('active','inactive')
    and (v_region_id is null or e.region_id is null or e.region_id=v_region_id)
    and p_acq_datetime between e.first_seen-make_interval(hours=>p_match_window_hours)
                           and e.last_seen+make_interval(hours=>p_match_window_hours)
    and extensions.st_dwithin(e.last_location,v_point,p_match_radius_m)
  order by extensions.st_distance(e.last_location,v_point),e.last_seen desc
  limit 1 for update;

  if v_event_id is null then
    insert into public.fire_events(
      region_id,status,lifecycle_status,first_seen,last_seen,
      first_latitude,first_longitude,last_latitude,last_longitude,
      first_location,last_location,best_latitude,best_longitude,best_location,
      best_location_resolution_m,observation_count,multisource_count,multisource_sources,
      match_radius_m,notification_required
    ) values(
      v_region_id,'active','active',p_acq_datetime,p_acq_datetime,
      p_latitude,p_longitude,p_latitude,p_longitude,
      v_point,v_point,p_latitude,p_longitude,v_point,p_resolution_m,
      1,1,array[coalesce(p_satellite,p_source)],p_match_radius_m,true
    ) returning id into v_event_id;
    v_new:=true;
  else
    update public.fire_events e set
      region_id=coalesce(e.region_id,v_region_id),
      status='active',lifecycle_status='active',
      first_seen=least(e.first_seen,p_acq_datetime),
      last_seen=greatest(e.last_seen,p_acq_datetime),
      last_latitude=case when p_acq_datetime>=e.last_seen then p_latitude else e.last_latitude end,
      last_longitude=case when p_acq_datetime>=e.last_seen then p_longitude else e.last_longitude end,
      last_location=case when p_acq_datetime>=e.last_seen then v_point else e.last_location end,
      best_latitude=case when e.best_location_resolution_m is null or coalesce(p_resolution_m,999999)<e.best_location_resolution_m then p_latitude else e.best_latitude end,
      best_longitude=case when e.best_location_resolution_m is null or coalesce(p_resolution_m,999999)<e.best_location_resolution_m then p_longitude else e.best_longitude end,
      best_location=case when e.best_location_resolution_m is null or coalesce(p_resolution_m,999999)<e.best_location_resolution_m then v_point else e.best_location end,
      best_location_resolution_m=least(coalesce(e.best_location_resolution_m,999999),coalesce(p_resolution_m,999999)),
      observation_count=e.observation_count+1,
      updated_at=now()
    where e.id=v_event_id;
  end if;

  update public.detections set event_id=v_event_id where id=v_detection_id;

  update public.fire_events e set
    multisource_sources=x.sources,
    multisource_count=cardinality(x.sources)
  from (
    select array_agg(distinct coalesce(nullif(satellite,''),source) order by coalesce(nullif(satellite,''),source)) sources
    from public.detections where event_id=v_event_id
  ) x
  where e.id=v_event_id;

  return jsonb_build_object(
    'inserted',true,'duplicate',false,'outside_aoi',false,
    'detection_id',v_detection_id,'event_id',v_event_id,'region_id',v_region_id,
    'is_new_event',v_new,'should_notify',v_new
  );
end;
$$;

create or replace function public.ingest_firms_batch(
  p_records jsonb,p_match_window_hours integer default 24
)
returns jsonb
language plpgsql security definer
set search_path=public,extensions,pg_temp
as $$
declare
  r jsonb; res jsonb;
  inserted_count integer:=0; duplicate_count integer:=0; outside_count integer:=0; new_event_count integer:=0;
begin
  if jsonb_typeof(p_records)<>'array' then raise exception 'p_records must be JSON array'; end if;
  for r in select value from jsonb_array_elements(p_records) loop
    res:=public.ingest_firms_detection(
      r->>'source',r->>'satellite',coalesce(r->>'instrument','VIIRS'),
      (r->>'acq_datetime')::timestamptz,(r->>'latitude')::double precision,(r->>'longitude')::double precision,
      nullif(r->>'scan','')::double precision,nullif(r->>'track','')::double precision,
      nullif(r->>'confidence',''),nullif(r->>'frp','')::double precision,nullif(r->>'daynight',''),
      r,coalesce((r->>'match_radius_m')::integer,750),p_match_window_hours,
      nullif(r->>'resolution_m','')::integer
    );
    if coalesce((res->>'inserted')::boolean,false) then inserted_count:=inserted_count+1; end if;
    if coalesce((res->>'duplicate')::boolean,false) then duplicate_count:=duplicate_count+1; end if;
    if coalesce((res->>'outside_aoi')::boolean,false) then outside_count:=outside_count+1; end if;
    if coalesce((res->>'is_new_event')::boolean,false) then new_event_count:=new_event_count+1; end if;
  end loop;
  return jsonb_build_object(
    'inserted',inserted_count,'duplicates',duplicate_count,
    'outside_aoi',outside_count,'new_events',new_event_count
  );
end;
$$;

create or replace function public.verify_firewatch_cron_secret(p_secret text)
returns boolean
language sql stable security definer
set search_path=public,vault,pg_temp
as $$
select coalesce((
  select p_secret=decrypted_secret from vault.decrypted_secrets
  where name='firewatch_cron_secret' limit 1
),false);
$$;

insert into public.system_state(key,value) values
('bootstrap',jsonb_build_object('done',false)),
('monitor_firms',jsonb_build_object('last_success_run',null,'last_error',null))
on conflict(key) do nothing;

alter table public.project_config enable row level security;
alter table public.monitoring_areas enable row level security;
alter table public.regions enable row level security;
alter table public.fire_events enable row level security;
alter table public.detections enable row level security;
alter table public.system_state enable row level security;
alter table public.firms_sources enable row level security;

revoke all on table public.project_config,public.monitoring_areas,public.regions,public.fire_events,public.detections,public.system_state,public.firms_sources from public,anon,authenticated;
grant select,insert,update,delete on table public.project_config,public.monitoring_areas,public.regions,public.fire_events,public.detections,public.system_state,public.firms_sources to service_role;
grant usage,select on all sequences in schema public to service_role;

revoke execute on function public.firewatch_runtime_config() from public,anon,authenticated;
revoke execute on function public.firewatch_point_in_aoi(double precision,double precision) from public,anon,authenticated;
revoke execute on function public.lookup_region_id(double precision,double precision) from public,anon,authenticated;
revoke execute on function public.firewatch_set_geography(jsonb,jsonb) from public,anon,authenticated;
revoke execute on function public.ingest_firms_detection(text,text,text,timestamptz,double precision,double precision,double precision,double precision,text,double precision,text,jsonb,integer,integer,integer) from public,anon,authenticated;
revoke execute on function public.ingest_firms_batch(jsonb,integer) from public,anon,authenticated;
revoke execute on function public.verify_firewatch_cron_secret(text) from public,anon,authenticated;

grant execute on function public.firewatch_runtime_config() to service_role;
grant execute on function public.firewatch_point_in_aoi(double precision,double precision) to service_role;
grant execute on function public.lookup_region_id(double precision,double precision) to service_role;
grant execute on function public.firewatch_set_geography(jsonb,jsonb) to service_role;
grant execute on function public.ingest_firms_detection(text,text,text,timestamptz,double precision,double precision,double precision,double precision,text,double precision,text,jsonb,integer,integer,integer) to service_role;
grant execute on function public.ingest_firms_batch(jsonb,integer) to service_role;
grant execute on function public.verify_firewatch_cron_secret(text) to service_role;
