import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "@supabase/supabase-js";
const FIRMS_BASE="https://firms.modaps.eosdis.nasa.gov/api/area/csv", SOURCE="MODIS_NRT", BBOX="21.5,43.5,41.5,53.5";
const LOOKBACK_DAYS=2, WINDOW_HOURS=24, MATCH_RADIUS_M=1000, MATCH_WINDOW_HOURS=24, BOOTSTRAP_FRESH_HOURS=3;
type Row=Record<string,string>;
function json(x:unknown,s=200){return new Response(JSON.stringify(x,null,2),{status:s,headers:{"content-type":"application/json; charset=utf-8"}})}
function line(s:string){const o:string[]=[];let v="",q=false;for(let i=0;i<s.length;i++){const c=s[i];if(c==='"'){if(q&&s[i+1]==='"'){v+='"';i++}else q=!q}else if(c===","&&!q){o.push(v);v=""}else v+=c}o.push(v);return o}
function csv(s:string):Row[]{const l=s.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean);if(l.length<2)return[];const h=line(l[0]).map(x=>x.trim());return l.slice(1).map(z=>{const a=line(z),r:Row={};h.forEach((k,i)=>r[k]=a[i]??"");return r})}
function acq(r:Row){const d=r.acq_date?.trim(),t=r.acq_time?.trim().padStart(4,"0");if(!d||!t||!/^\d{4}-\d{2}-\d{2}$/.test(d)||!/^\d{4}$/.test(t))return null;const x=new Date(`${d}T${t.slice(0,2)}:${t.slice(2,4)}:00Z`);return Number.isNaN(x.getTime())?null:x}
function conf(v:string){const n=Number(v);return !Number.isFinite(n)?"":n>=80?"h":n>=30?"n":"l"}
async function fetchData(key:string,now:Date){const u=`${FIRMS_BASE}/${encodeURIComponent(key)}/${SOURCE}/${BBOX}/${LOOKBACK_DAYS}`;const res=await fetch(u,{headers:{"user-agent":"firewatch-modis/2.0"},signal:AbortSignal.timeout(30000)}),body=await res.text();if(!res.ok)throw new Error(`${SOURCE}: FIRMS HTTP ${res.status}: ${body.slice(0,300)}`);const rows=csv(body),cut=now.getTime()-WINDOW_HOURS*3600000,future=now.getTime()+600000,records:any[]=[];for(const r of rows){const d=acq(r);if(!d||d.getTime()<cut||d.getTime()>future)continue;const lat=Number(r.latitude),lon=Number(r.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon))continue;records.push({source:SOURCE,satellite:r.satellite??"",instrument:r.instrument||"MODIS",acq_datetime:d.toISOString(),latitude:String(lat),longitude:String(lon),scan:r.scan??"",track:r.track??"",confidence:conf(r.confidence??""),confidence_original:r.confidence??"",frp:r.frp??"",daynight:r.daynight??"",resolution_m:1000})}return{records,fetched:rows.length}}
Deno.serve(async(req)=>{if(req.method!=="POST")return json({ok:false,error:"Требуется POST-запрос"},405);const mapKey=Deno.env.get("FIRMS_MAP_KEY"),url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!mapKey||!url||!key)return json({ok:false,error:"Отсутствует обязательная настройка среды"},500);const sb=createClient(url,key,{auth:{persistSession:false}}),secret=req.headers.get("x-cron-secret")??"";const {data:ok,error:ae}=await sb.rpc("verify_firewatch_cron_secret",{p_secret:secret});if(ae||ok!==true)return json({ok:false,error:"Нет доступа"},401);const started=new Date();try{const {data:state}=await sb.from("system_state").select("value").eq("key","modis_bootstrap").maybeSingle(),bootstrapDone=Boolean(state?.value?.done),source=await fetchData(mapKey,started);const {data:batch,error:be}=await sb.rpc("ingest_firms_batch",{p_records:source.records,p_match_radius_m:MATCH_RADIUS_M,p_match_window_hours:MATCH_WINDOW_HOURS});if(be)throw be;let suppressed=0,freshKept=0;if(!bootstrapDone){const cutoff=started.getTime()-BOOTSTRAP_FRESH_HOURS*3600000,notes=batch?.notifications??[],stale=notes.filter((x:any)=>new Date(x.acq_datetime).getTime()<cutoff).map((x:any)=>x.event_id).filter(Boolean);freshKept=notes.length-stale.length;if(stale.length){const {error:e}=await sb.from("fire_events").update({notification_required:false}).in("id",stale);if(e)throw e;suppressed=stale.length}await sb.from("system_state").upsert({key:"modis_bootstrap",value:{done:true,completed_at:new Date().toISOString(),fresh_window_hours:BOOTSTRAP_FRESH_HOURS,suppressed_initial_events:suppressed,fresh_initial_events_kept:freshKept},updated_at:new Date().toISOString()})}const monitor={last_success_run:new Date().toISOString(),last_error:null,source:SOURCE,resolution_m:1000,satellites:"Terra/Aqua",match_radius_m:MATCH_RADIUS_M,fetched_rows:source.fetched,recent_rows:source.records.length,inserted:batch?.inserted??0,duplicates:batch?.duplicates??0,outside_ukraine:batch?.outside_ukraine??0,new_events:batch?.new_events??0,notify_count:bootstrapDone?(batch?.notify_count??0):freshKept,bootstrap_was_done:bootstrapDone,bootstrap_fresh_window_hours:BOOTSTRAP_FRESH_HOURS,initial_notifications_suppressed:suppressed,initial_fresh_events_kept:freshKept};await sb.from("system_state").upsert({key:"monitor_modis",value:monitor,updated_at:new Date().toISOString()});return json({ok:true,mode:bootstrapDone?"monitor":"bootstrap",started_at_utc:started.toISOString(),source:{source:SOURCE,resolution_m:1000,satellites:"Terra/Aqua",fetched_rows:source.fetched,recent_rows:source.records.length},batch,initial_notifications_suppressed:suppressed,initial_fresh_events_kept:freshKept})}catch(e){const m=e instanceof Error?e.message:String(e);try{await sb.from("system_state").upsert({key:"monitor_modis",value:{last_error:m,failed_at:new Date().toISOString()},updated_at:new Date().toISOString()})}catch{}return json({ok:false,error:m,started_at_utc:started.toISOString()},502)}});
